from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import json

from PIL import Image
from torch.utils.data import Dataset


DEFAULT_DATASET_ROOT = Path(
    "data/remote_sensing/"
    "rs_vqa_evidence_grounded"
)


@dataclass(frozen=True)
class EvidenceGroundedRSVQAExample:
    """
    One evidence-grounded remote-sensing VQA example.

    The RGB PNG is the VLM-facing representation.

    The original multispectral .npy patch is retained
    separately for downstream GIS/specialist processing.

    Ground truth is retained for evaluation and must
    never be treated as an authority generated by the
    language model.
    """

    example_id: str
    image: Path
    source_raster_patch: Path
    question: str
    evidence: str
    answer: str
    task: str
    source: str
    ground_truth: dict[str, Any]
    image_representation: dict[str, Any]


class EvidenceGroundedRSVQADataset(
    Dataset[EvidenceGroundedRSVQAExample]
):
    """
    Dataset loader for the evidence-grounded RS-VQA
    development dataset.

    Expected JSONL fields:

        id
        image
        source_raster_patch
        question
        evidence
        answer
        task
        source
        ground_truth
        image_representation
    """

    REQUIRED_FIELDS = {
        "id",
        "image",
        "source_raster_patch",
        "question",
        "evidence",
        "answer",
        "task",
        "source",
        "ground_truth",
        "image_representation",
    }

    def __init__(
        self,
        jsonl_path: str | Path,
    ) -> None:

        self.jsonl_path = Path(
            jsonl_path
        )

        if not self.jsonl_path.exists():
            raise FileNotFoundError(
                self.jsonl_path
            )

        self.examples = self._load()

    def _load(
        self,
    ) -> list[
        EvidenceGroundedRSVQAExample
    ]:

        examples = []

        for line_number, line in enumerate(
            self.jsonl_path.read_text(
                encoding="utf-8"
            ).splitlines(),
            start=1,
        ):

            if not line.strip():
                continue

            record = json.loads(line)

            missing = (
                self.REQUIRED_FIELDS
                - set(record)
            )

            if missing:
                raise ValueError(
                    f"Line {line_number}: "
                    f"missing fields {sorted(missing)}"
                )

            image = Path(
                record["image"]
            )

            source_raster_patch = Path(
                record[
                    "source_raster_patch"
                ]
            )

            if not image.exists():
                raise FileNotFoundError(
                    f"Line {line_number}: "
                    f"image does not exist: "
                    f"{image}"
                )

            if not source_raster_patch.exists():
                raise FileNotFoundError(
                    f"Line {line_number}: "
                    f"source raster patch does "
                    f"not exist: "
                    f"{source_raster_patch}"
                )

            if image.suffix.lower() != ".png":
                raise ValueError(
                    f"Line {line_number}: "
                    f"VLM image must be PNG: "
                    f"{image}"
                )

            if (
                source_raster_patch
                .suffix.lower()
                != ".npy"
            ):
                raise ValueError(
                    f"Line {line_number}: "
                    f"source raster patch must "
                    f"be NumPy .npy: "
                    f"{source_raster_patch}"
                )

            question = record[
                "question"
            ]

            evidence = record[
                "evidence"
            ]

            answer = record[
                "answer"
            ]

            if not isinstance(
                question,
                str,
            ) or not question.strip():
                raise ValueError(
                    f"Line {line_number}: "
                    "question must be non-empty"
                )

            if not isinstance(
                evidence,
                str,
            ) or not evidence.strip():
                raise ValueError(
                    f"Line {line_number}: "
                    "evidence must be non-empty"
                )

            if not isinstance(
                answer,
                str,
            ) or not answer.strip():
                raise ValueError(
                    f"Line {line_number}: "
                    "answer must be non-empty"
                )

            examples.append(
                EvidenceGroundedRSVQAExample(
                    example_id=str(
                        record["id"]
                    ),
                    image=image,
                    source_raster_patch=(
                        source_raster_patch
                    ),
                    question=question,
                    evidence=evidence,
                    answer=answer,
                    task=str(
                        record["task"]
                    ),
                    source=str(
                        record["source"]
                    ),
                    ground_truth=dict(
                        record["ground_truth"]
                    ),
                    image_representation=dict(
                        record[
                            "image_representation"
                        ]
                    ),
                )
            )

        if not examples:
            raise ValueError(
                f"No examples found in "
                f"{self.jsonl_path}"
            )

        return examples

    def __len__(self) -> int:
        return len(self.examples)

    def __getitem__(
        self,
        index: int,
    ) -> EvidenceGroundedRSVQAExample:

        return self.examples[index]

    @staticmethod
    def load_image(
        example:
            EvidenceGroundedRSVQAExample,
    ) -> Image.Image:

        image = Image.open(
            example.image
        ).convert("RGB")

        return image

    @staticmethod
    def build_qwen_user_content(
        example:
            EvidenceGroundedRSVQAExample,
    ) -> list[dict[str, Any]]:
        """
        Build the multimodal user content.

        Image is supplied separately from text so
        Qwen's processor can construct the correct
        multimodal input representation.
        """

        text = (
            "Remote-sensing evidence:\n"
            f"{example.evidence}\n\n"
            "Question:\n"
            f"{example.question}"
        )

        return [
            {
                "type": "image",
            },
            {
                "type": "text",
                "text": text,
            },
        ]

    @staticmethod
    def build_qwen_messages(
        example:
            EvidenceGroundedRSVQAExample,
    ) -> list[dict[str, Any]]:
        """
        Build the complete supervised conversation.

        The assistant answer is the training target.
        """

        user_content = (
            EvidenceGroundedRSVQADataset
            .build_qwen_user_content(
                example
            )
        )

        return [
            {
                "role": "user",
                "content": user_content,
            },
            {
                "role": "assistant",
                "content": [
                    {
                        "type": "text",
                        "text": example.answer,
                    }
                ],
            },
        ]

    @staticmethod
    def build_qwen_prompt_messages(
        example:
            EvidenceGroundedRSVQAExample,
    ) -> list[dict[str, Any]]:
        """
        Build only the user side.

        Used during generation/evaluation.
        """

        user_content = (
            EvidenceGroundedRSVQADataset
            .build_qwen_user_content(
                example
            )
        )

        return [
            {
                "role": "user",
                "content": user_content,
            }
        ]


def load_train_dataset(
    root: str | Path = DEFAULT_DATASET_ROOT,
) -> EvidenceGroundedRSVQADataset:

    root = Path(root)

    return EvidenceGroundedRSVQADataset(
        root / "train.jsonl"
    )


def load_validation_dataset(
    root: str | Path = DEFAULT_DATASET_ROOT,
) -> EvidenceGroundedRSVQADataset:

    root = Path(root)

    return EvidenceGroundedRSVQADataset(
        root / "val.jsonl"
    )
